Site settings
title: nan太 club             
description: "nan太的stucky仓库"    

SNS settings      
github_username: nantaistucky
weibo_username: nan太

cdn-url: "https://nantai.club/"

# Qiniu imageView2 API
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/300/h/300/interlace/1/q/90"
clip-post: "?" # you can custom post width and height
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

#post default images
post-default-img: post-default.jpg

# friends
friends: [
	{
		title: "your friend title",
		href: "your fiend path"
	},
	{
		title: "your friend title 2",
		href: "your friend path 2"
	}
] 
